### PR TITLE
Add health method that returns the healthcheck result

### PR DESCRIPTION
**Pull request by awikkerink**

### CODE REVIEW

**Comment by omsmith** [comment]
What's the intention for this one? If it's for usage in a dependent's healthcheck, not sure that's a great idea - don't want recursive healthchecks going on.

**Comment by awikkerink** [comment]
I suppose. It is to ensure that landlord is configured correctly for the hypermedia-proxy.

**Comment by omsmith** [comment]
Perhaps consider adding a `ping` route or something? In [node-auth-validation](https://github.com/Brightspace/node-auth-validation/blob/master/src/index.js#L258) we just do the process we actually want to be doing to verify things are good.

**Comment by awikkerink** [comment]
What do you think about https://github.com/apaszke/tcp-ping?

**Pull request closed without merging**
